name: dogs_client_application
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  loadmore: ^1.0.4
  transparent_image: ^1.0.0
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.4
#  firebase_database: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/google_logo.png
    - assets/dog_placeholder.png